# Generated by Django 4.1.6 on 2024-05-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarKunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='daftar_kunjungan_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
