# Generated by Django 4.1.6 on 2024-05-29 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_daftarkunjungan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDaftarKunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daftar_kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.daftarkunjungan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
