# Generated by Django 4.1.6 on 2024-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_remove_question_nama_penanya_question_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='poin_keaktifan',
            field=models.IntegerField(default=0),
        ),
    ]
