# Generated by Django 4.1.6 on 2024-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_pengguna_poin_keaktifan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='myFirstApp.tag'),
        ),
    ]
