# Generated by Django 4.1.6 on 2024-05-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
